version: 2.1

orbs:
  architect: giantswarm/architect@4.6.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: config-controller
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-config-controller-to-quay
          image: "quay.io/giantswarm/config-controller"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-config-controller-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/config-controller"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/


      - architect/push-to-app-catalog:
          context: "architect"
          name: push-config-controller-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "config-controller"
          requires:
            - push-config-controller-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-config-controller-to-shared-app-collection
          context: architect
          app_name: "config-controller"
          app_namespace: "giantswarm"
          app_collection_repo: "shared-app-collection"
          requires:
            - push-config-controller-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-config-controller-to-aws-app-collection
          context: architect
          app_name: "config-controller"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-config-controller-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-config-controller-to-azure-app-collection
          context: architect
          app_name: "config-controller"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-config-controller-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-config-controller-to-kvm-app-collection
          context: architect
          app_name: "config-controller"
          app_namespace: "giantswarm"
          app_collection_repo: "kvm-app-collection"
          requires:
            - push-config-controller-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-config-controller-to-vmware-app-collection
          context: architect
          app_name: "config-controller"
          app_namespace: "giantswarm"
          app_collection_repo: "vmware-app-collection"
          requires:
            - push-config-controller-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
